In [1]:
import numpy as np

In [2]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [4]:
b=np.matrix([[1,2],[3,4]])
b

matrix([[1, 2],
        [3, 4]])

In [5]:
a@a


array([[ 7, 10],
       [15, 22]])

In [6]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [7]:
np.multiply(a,a
           )

array([[ 1,  4],
       [ 9, 16]])

In [8]:
np.prod(a)

24

In [2]:
my_array=np.array([1,2,3])
my_array+5

array([6, 7, 8])

In [3]:
c=np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
d=np.array([5,6,7])
c+d

array([[6., 7., 8.],
       [6., 7., 8.],
       [6., 7., 8.]])

In [5]:
g=np.ones((3,1))
g

array([[1.],
       [1.],
       [1.]])

In [6]:
n=np.array([5,6,7])
g+n

array([[6., 7., 8.],
       [6., 7., 8.],
       [6., 7., 8.]])

In [6]:
np.sum(a)

10

In [9]:
np.cumsum(a , axis=1)

array([[1, 3],
       [3, 7]], dtype=int32)

In [10]:
np.subtract(a,a)

array([[0, 0],
       [0, 0]])

In [11]:
np.divide([5,6,7],3)

array([1.66666667, 2.        , 2.33333333])

In [12]:
np.floor_divide([5,6,7],3)

array([1, 2, 2], dtype=int32)

In [13]:
np.math.sqrt(5)

2.23606797749979

In [15]:
np.math.nan

nan

In [16]:
np.math.inf

inf

In [17]:
np.random.uniform(1,5,(2,3))

array([[4.22488664, 2.33469049, 4.72853304],
       [1.22376188, 2.8834015 , 1.81119023]])

In [18]:
np.random.standard_normal((2,1))

array([[-0.68271083],
       [ 1.05100039]])

In [3]:
np.arange(1,10,3)

array([1, 4, 7])

In [4]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [5]:
my_mask=a>2
a[my_mask]

array([3, 4])

In [6]:
my_mask2=np.logical_(a>1,a<4)

In [7]:
a[my_mask2]

array([2, 3])

In [8]:
np.ones((1,3))

array([[1., 1., 1.]])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
np.size(a)

4

In [12]:
np.shape(a)

(2, 2)

In [13]:
aa=np.array([1,2,3,4,1,3])
aa

array([1, 2, 3, 4, 1, 3])

In [14]:
bb=([7,8,9,1,3])

In [15]:
bb

[7, 8, 9, 1, 3]

In [16]:
np.unique(a)

array([1, 2, 3, 4])

In [17]:
np.union1d(aa,bb)

array([1, 2, 3, 4, 7, 8, 9])

In [18]:
np.intersect1d(aa,bb)

array([1, 3])

In [19]:
np.mean(aa)

2.3333333333333335

In [20]:
np.median(aa)

2.5

In [21]:
np.std(aa)

1.1055415967851334

In [22]:
np.var(aa)

1.2222222222222223

In [24]:
chandJomleii=np.array([1,2,2])

In [26]:
np.polyval(chandJomleii,2)

10

In [27]:
np.polyder(chandJomleii)

array([2, 2])

In [28]:
np.polyint(chandJomleii)

array([0.33333333, 1.        , 2.        , 0.        ])