In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.sparse import csr_matrix
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
doc = ['you are watching machine learning course',
       'word frequency array is a part of unsupervised learning from machine learning course',
       'PLP is an online educational channel in youtube']
titles = ['first doc', 'second doc', 'third doc']

In [3]:
tfidf=TfidfVectorizer()
csr_mat=tfidf.fit_transform(doc)

In [4]:
from sklearn.decomposition  import NMF

In [5]:
nmf=NMF(n_components=2)
nmf.fit(csr_mat)
nmf_transformed=nmf.transform(csr_mat)

In [6]:
pd.DataFrame(nmf.components_,columns=sorted(tfidf.vocabulary_))

an       are     array   channel   course  educational  frequency  \
0  0.000000  0.307233  0.199014  0.000000  0.38514     0.000000   0.199014   
1  0.356132  0.000000  0.006071  0.356132  0.00000     0.356132   0.006071   

       from        in        is  ...  machine        of    online      part  \
0  0.199014  0.000000  0.143910  ...  0.38514  0.199014  0.000000  0.199014   
1  0.006071  0.356132  0.275688  ...  0.00000  0.006071  0.356132  0.006071   

        plp  unsupervised  watching      word       you   youtube  
0  0.000000      0.199014  0.307233  0.199014  0.307233  0.000000  
1  0.356132      0.006071  0.000000  0.006071  0.000000  0.356132  

[2 rows x 21 columns]

In [7]:
nmf_transformed

array([[0.75517503, 0.        ],
       [0.74784285, 0.04148458],
       [0.        , 1.01830894]])

In [8]:
nmf_df=pd.DataFrame(nmf_transformed,index=titles)
nmf_df

0         1
first doc   0.755175  0.000000
second doc  0.747843  0.041485
third doc   0.000000  1.018309

In [9]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
mat_nmf=NMF(n_components=2)
mat_nmf.fit(mat)
nmf_features=mat_nmf.transform(mat)
nmf_features

array([[0.49770353, 2.01555509],
       [1.9886994 , 1.00775116],
       [3.47968482, 0.        ]])

In [10]:
mat_nmf.components_

array([[2.01166962, 2.29905988, 2.58644549],
       [0.        , 0.42480675, 0.84963252]])

In [11]:
np.dot(nmf_features,mat_nmf.components_)

array([[1.00121507, 2.00047162, 2.99976419],
       [4.00060618, 5.0002385 , 5.99988075],
       [6.99997626, 8.00000376, 9.00001512]])